openapi: "3.0.2"
info:
  version: "1.0"
  title: Welcome to the Grade Scale API!
  description: This API allows users to view the grade scale
servers:
  - url: "http://localhost:5001/api"
    description: Development server
paths:
  /grade-scale:
    get:
      summary: Returns the grade scale
      description: Get the grade scale
      operationId: get-grade-scale
      tags:
        - grade-scale
      
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GradeScaleArray'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    GradeScaleArray:
      type: array
      items:
        $ref: "#/components/schemas/Grade"
    Grade:
      type: object
      properties:
        id:
          type: number
        level:
          type: string
          enum: [Level 5, Level 6]
        min_mark:
          type: number
          minimum: 0
          maximum: 100
        max_mark:
          type: number
          minimum: 0
          maximum: 100
        grade:
          type: string
          enum: [A+, A, A-, B+, B, B-, C+, C, C-, D, E]
      required:
        - id
        - level
        - min_mark
        - max_mark
        - grade
    Error:
      type: object
      properties:
        message:
          type: string
          description: Internal Server Error
tags:
  - name: grade-scale
